// commentActionType.js

// Tạo mới bình luận
export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';

// Cập nhật bình luận
export const UPDATE_COMMENT_REQUEST = 'UPDATE_COMMENT_REQUEST';
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';
export const UPDATE_COMMENT_FAILURE = 'UPDATE_COMMENT_FAILURE';

// Xóa bình luận
export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';

// Lấy tất cả bình luận của người dùng
export const GET_COMMENTS_BY_USER_REQUEST = 'GET_COMMENTS_BY_USER_REQUEST';
export const GET_COMMENTS_BY_USER_SUCCESS = 'GET_COMMENTS_BY_USER_SUCCESS';
export const GET_COMMENTS_BY_USER_FAILURE = 'GET_COMMENTS_BY_USER_FAILURE';

// Lấy tất cả bình luận của sản phẩm
export const GET_COMMENTS_BY_PRODUCT_REQUEST = 'GET_COMMENTS_BY_PRODUCT_REQUEST';
export const GET_COMMENTS_BY_PRODUCT_SUCCESS = 'GET_COMMENTS_BY_PRODUCT_SUCCESS';
export const GET_COMMENTS_BY_PRODUCT_FAILURE = 'GET_COMMENTS_BY_PRODUCT_FAILURE';

// Lấy tất cả bình luận
export const GET_ALL_COMMENTS_REQUEST = 'GET_ALL_COMMENTS_REQUEST';
export const GET_ALL_COMMENTS_SUCCESS = 'GET_ALL_COMMENTS_SUCCESS';
export const GET_ALL_COMMENTS_FAILURE = 'GET_ALL_COMMENTS_FAILURE';

// Lấy một bình luận cụ thể theo ID
export const GET_COMMENT_BY_ID_REQUEST = 'GET_COMMENT_BY_ID_REQUEST';
export const GET_COMMENT_BY_ID_SUCCESS = 'GET_COMMENT_BY_ID_SUCCESS';
export const GET_COMMENT_BY_ID_FAILURE = 'GET_COMMENT_BY_ID_FAILURE';