// orderDetailActionType.js

// Tạo mới chi tiết đơn hàng
export const CREATE_ORDER_DETAIL_REQUEST = 'CREATE_ORDER_DETAIL_REQUEST';
export const CREATE_ORDER_DETAIL_SUCCESS = 'CREATE_ORDER_DETAIL_SUCCESS';
export const CREATE_ORDER_DETAIL_FAILURE = 'CREATE_ORDER_DETAIL_FAILURE';

// Lấy tất cả chi tiết đơn hàng
export const GET_ALL_ORDER_DETAILS_REQUEST = 'GET_ALL_ORDER_DETAILS_REQUEST';
export const GET_ALL_ORDER_DETAILS_SUCCESS = 'GET_ALL_ORDER_DETAILS_SUCCESS';
export const GET_ALL_ORDER_DETAILS_FAILURE = 'GET_ALL_ORDER_DETAILS_FAILURE';

// Lấy chi tiết đơn hàng theo ID
export const GET_ORDER_DETAIL_BY_ID_REQUEST = 'GET_ORDER_DETAIL_BY_ID_REQUEST';
export const GET_ORDER_DETAIL_BY_ID_SUCCESS = 'GET_ORDER_DETAIL_BY_ID_SUCCESS';
export const GET_ORDER_DETAIL_BY_ID_FAILURE = 'GET_ORDER_DETAIL_BY_ID_FAILURE';

// Cập nhật chi tiết đơn hàng
export const UPDATE_ORDER_DETAIL_REQUEST = 'UPDATE_ORDER_DETAIL_REQUEST';
export const UPDATE_ORDER_DETAIL_SUCCESS = 'UPDATE_ORDER_DETAIL_SUCCESS';
export const UPDATE_ORDER_DETAIL_FAILURE = 'UPDATE_ORDER_DETAIL_FAILURE';

// Xóa chi tiết đơn hàng
export const DELETE_ORDER_DETAIL_REQUEST = 'DELETE_ORDER_DETAIL_REQUEST';
export const DELETE_ORDER_DETAIL_SUCCESS = 'DELETE_ORDER_DETAIL_SUCCESS';
export const DELETE_ORDER_DETAIL_FAILURE = 'DELETE_ORDER_DETAIL_FAILURE';