// paymentActionType.js

// Yêu cầu thanh toán VNPay
export const CREATE_PAYMENT_REQUEST = 'CREATE_PAYMENT_REQUEST';
export const CREATE_PAYMENT_SUCCESS = 'CREATE_PAYMENT_SUCCESS';
export const CREATE_PAYMENT_FAILURE = 'CREATE_PAYMENT_FAILURE';

// Xử lý kết quả thanh toán từ VNPay
export const PAYMENT_RETURN_REQUEST = 'PAYMENT_RETURN_REQUEST';
export const PAYMENT_RETURN_SUCCESS = 'PAYMENT_RETURN_SUCCESS';
export const PAYMENT_RETURN_FAILURE = 'PAYMENT_RETURN_FAILURE';

// Lấy lịch sử thanh toán của người dùng
export const GET_PAYMENT_HISTORY_REQUEST = 'GET_PAYMENT_HISTORY_REQUEST';
export const GET_PAYMENT_HISTORY_SUCCESS = 'GET_PAYMENT_HISTORY_SUCCESS';
export const GET_PAYMENT_HISTORY_FAILURE = 'GET_PAYMENT_HISTORY_FAILURE';