// productVariantActionType.js

// Fetch all product variants
export const GET_PRODUCT_VARIANTS_REQUEST = 'GET_PRODUCT_VARIANTS_REQUEST';
export const GET_PRODUCT_VARIANTS_SUCCESS = 'GET_PRODUCT_VARIANTS_SUCCESS';
export const GET_PRODUCT_VARIANTS_FAILURE = 'GET_PRODUCT_VARIANTS_FAILURE';

// Create a new product variant
export const CREATE_PRODUCT_VARIANT_REQUEST = 'CREATE_PRODUCT_VARIANT_REQUEST';
export const CREATE_PRODUCT_VARIANT_SUCCESS = 'CREATE_PRODUCT_VARIANT_SUCCESS';
export const CREATE_PRODUCT_VARIANT_FAILURE = 'CREATE_PRODUCT_VARIANT_FAILURE';

// Update a product variant
export const UPDATE_PRODUCT_VARIANT_REQUEST = 'UPDATE_PRODUCT_VARIANT_REQUEST';
export const UPDATE_PRODUCT_VARIANT_SUCCESS = 'UPDATE_PRODUCT_VARIANT_SUCCESS';
export const UPDATE_PRODUCT_VARIANT_FAILURE = 'UPDATE_PRODUCT_VARIANT_FAILURE';

// Delete a product variant
export const DELETE_PRODUCT_VARIANT_REQUEST = 'DELETE_PRODUCT_VARIANT_REQUEST';
export const DELETE_PRODUCT_VARIANT_SUCCESS = 'DELETE_PRODUCT_VARIANT_SUCCESS';
export const DELETE_PRODUCT_VARIANT_FAILURE = 'DELETE_PRODUCT_VARIANT_FAILURE';