// ratingActionType.js

// Tạo mới đánh giá
export const CREATE_RATING_REQUEST = 'CREATE_RATING_REQUEST';
export const CREATE_RATING_SUCCESS = 'CREATE_RATING_SUCCESS';
export const CREATE_RATING_FAILURE = 'CREATE_RATING_FAILURE';

// Lấy tất cả các đánh giá
export const GET_ALL_RATINGS_REQUEST = 'GET_ALL_RATINGS_REQUEST';
export const GET_ALL_RATINGS_SUCCESS = 'GET_ALL_RATINGS_SUCCESS';
export const GET_ALL_RATINGS_FAILURE = 'GET_ALL_RATINGS_FAILURE';

// Lấy một đánh giá cụ thể theo ID
export const GET_RATING_BY_ID_REQUEST = 'GET_RATING_BY_ID_REQUEST';
export const GET_RATING_BY_ID_SUCCESS = 'GET_RATING_BY_ID_SUCCESS';
export const GET_RATING_BY_ID_FAILURE = 'GET_RATING_BY_ID_FAILURE';

// Lấy các đánh giá của một người dùng
export const GET_RATINGS_BY_USER_REQUEST = 'GET_RATINGS_BY_USER_REQUEST';
export const GET_RATINGS_BY_USER_SUCCESS = 'GET_RATINGS_BY_USER_SUCCESS';
export const GET_RATINGS_BY_USER_FAILURE = 'GET_RATINGS_BY_USER_FAILURE';

// Lấy tất cả các đánh giá của một sản phẩm
export const GET_RATINGS_BY_PRODUCT_REQUEST = 'GET_RATINGS_BY_PRODUCT_REQUEST';
export const GET_RATINGS_BY_PRODUCT_SUCCESS = 'GET_RATINGS_BY_PRODUCT_SUCCESS';
export const GET_RATINGS_BY_PRODUCT_FAILURE = 'GET_RATINGS_BY_PRODUCT_FAILURE';

// Cập nhật đánh giá
export const UPDATE_RATING_REQUEST = 'UPDATE_RATING_REQUEST';
export const UPDATE_RATING_SUCCESS = 'UPDATE_RATING_SUCCESS';
export const UPDATE_RATING_FAILURE = 'UPDATE_RATING_FAILURE';

// Xóa đánh giá
export const DELETE_RATING_REQUEST = 'DELETE_RATING_REQUEST';
export const DELETE_RATING_SUCCESS = 'DELETE_RATING_SUCCESS';
export const DELETE_RATING_FAILURE = 'DELETE_RATING_FAILURE';