// uploadImageActionType.js

// Tải lên một ảnh đơn
export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE';

// Tải lên nhiều ảnh
export const UPLOAD_MULTIPLE_IMAGES_REQUEST = 'UPLOAD_MULTIPLE_IMAGES_REQUEST';
export const UPLOAD_MULTIPLE_IMAGES_SUCCESS = 'UPLOAD_MULTIPLE_IMAGES_SUCCESS';
export const UPLOAD_MULTIPLE_IMAGES_FAILURE = 'UPLOAD_MULTIPLE_IMAGES_FAILURE';

// Lấy URL ảnh theo publicId
export const GET_IMAGE_URL_REQUEST = 'GET_IMAGE_URL_REQUEST';
export const GET_IMAGE_URL_SUCCESS = 'GET_IMAGE_URL_SUCCESS';
export const GET_IMAGE_URL_FAILURE = 'GET_IMAGE_URL_FAILURE';

// Xóa ảnh theo publicId
export const DELETE_IMAGE_REQUEST = 'DELETE_IMAGE_REQUEST';
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
export const DELETE_IMAGE_FAILURE = 'DELETE_IMAGE_FAILURE';

// Cập nhật ảnh
export const UPDATE_IMAGE_REQUEST = 'UPDATE_IMAGE_REQUEST';
export const UPDATE_IMAGE_SUCCESS = 'UPDATE_IMAGE_SUCCESS';
export const UPDATE_IMAGE_FAILURE = 'UPDATE_IMAGE_FAILURE';