// userActionType.js

// Lấy thông tin hồ sơ người dùng
export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';

// Cập nhật hồ sơ người dùng
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

// Gửi email xác thực
export const SEND_VERIFICATION_EMAIL_REQUEST = 'SEND_VERIFICATION_EMAIL_REQUEST';
export const SEND_VERIFICATION_EMAIL_SUCCESS = 'SEND_VERIFICATION_EMAIL_SUCCESS';
export const SEND_VERIFICATION_EMAIL_FAILURE = 'SEND_VERIFICATION_EMAIL_FAILURE';

// Xác minh email
export const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILURE = 'VERIFY_EMAIL_FAILURE';

// Tạo người dùng (Admin)
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

// Cập nhật người dùng (Admin)
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

// Xóa người dùng (Admin)
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

// Lấy người dùng theo ID
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

// Lấy danh sách người dùng với tìm kiếm và lọc
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

// Thêm phiếu giảm giá cho người dùng
export const ADD_VOUCHER_REQUEST = 'ADD_VOUCHER_REQUEST';
export const ADD_VOUCHER_SUCCESS = 'ADD_VOUCHER_SUCCESS';
export const ADD_VOUCHER_FAILURE = 'ADD_VOUCHER_FAILURE';

// Loại bỏ phiếu giảm giá của người dùng
export const REMOVE_VOUCHER_REQUEST = 'REMOVE_VOUCHER_REQUEST';
export const REMOVE_VOUCHER_SUCCESS = 'REMOVE_VOUCHER_SUCCESS';
export const REMOVE_VOUCHER_FAILURE = 'REMOVE_VOUCHER_FAILURE';

// Thêm sản phẩm yêu thích cho người dùng
export const ADD_FAVORITE_PRODUCT_REQUEST = 'ADD_FAVORITE_PRODUCT_REQUEST';
export const ADD_FAVORITE_PRODUCT_SUCCESS = 'ADD_FAVORITE_PRODUCT_SUCCESS';
export const ADD_FAVORITE_PRODUCT_FAILURE = 'ADD_FAVORITE_PRODUCT_FAILURE';

// Loại bỏ sản phẩm yêu thích của người dùng
export const REMOVE_FAVORITE_PRODUCT_REQUEST = 'REMOVE_FAVORITE_PRODUCT_REQUEST';
export const REMOVE_FAVORITE_PRODUCT_SUCCESS = 'REMOVE_FAVORITE_PRODUCT_SUCCESS';
export const REMOVE_FAVORITE_PRODUCT_FAILURE = 'REMOVE_FAVORITE_PRODUCT_FAILURE';