// voucherActionTypes.js

// Lấy danh sách phiếu giảm giá
export const FETCH_VOUCHERS_REQUEST = 'FETCH_VOUCHERS_REQUEST';
export const FETCH_VOUCHERS_SUCCESS = 'FETCH_VOUCHERS_SUCCESS';
export const FETCH_VOUCHERS_FAILURE = 'FETCH_VOUCHERS_FAILURE';

// Lấy phiếu giảm giá theo mã
export const FETCH_VOUCHER_BY_CODE_REQUEST = 'FETCH_VOUCHER_BY_CODE_REQUEST';
export const FETCH_VOUCHER_BY_CODE_SUCCESS = 'FETCH_VOUCHER_BY_CODE_SUCCESS';
export const FETCH_VOUCHER_BY_CODE_FAILURE = 'FETCH_VOUCHER_BY_CODE_FAILURE';

// Tạo mới phiếu giảm giá
export const CREATE_VOUCHER_REQUEST = 'CREATE_VOUCHER_REQUEST';
export const CREATE_VOUCHER_SUCCESS = 'CREATE_VOUCHER_SUCCESS';
export const CREATE_VOUCHER_FAILURE = 'CREATE_VOUCHER_FAILURE';

// Cập nhật phiếu giảm giá
export const UPDATE_VOUCHER_REQUEST = 'UPDATE_VOUCHER_REQUEST';
export const UPDATE_VOUCHER_SUCCESS = 'UPDATE_VOUCHER_SUCCESS';
export const UPDATE_VOUCHER_FAILURE = 'UPDATE_VOUCHER_FAILURE';

// Xóa phiếu giảm giá
export const DELETE_VOUCHER_REQUEST = 'DELETE_VOUCHER_REQUEST';
export const DELETE_VOUCHER_SUCCESS = 'DELETE_VOUCHER_SUCCESS';
export const DELETE_VOUCHER_FAILURE = 'DELETE_VOUCHER_FAILURE';

// Lấy phiếu giảm giá theo người dùng
export const GET_VOUCHERS_BY_USER_REQUEST = 'GET_VOUCHERS_BY_USER_REQUEST';
export const GET_VOUCHERS_BY_USER_SUCCESS = 'GET_VOUCHERS_BY_USER_SUCCESS';
export const GET_VOUCHERS_BY_USER_FAILURE = 'GET_VOUCHERS_BY_USER_FAILURE';